# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IBPSA Project 1
email: MWetter@lbl.gov
description: > # this means to ignore newlines until "baseurl:"
  Modelica Challenge Problems
domain: ibpsa.github.io
baseurl: /modelica-challenge-problems # the subpath of your site, e.g. /blog
url: https://ibpsa.github.io # the base hostname & protocol for your site
twitter_username:
github_username:  ibpsa/project1

collections:
  cases:
    output: true

future: true
# Build settings
markdown: kramdown
